name: wipac ci/cd

on: [ push ]

jobs:

  #############################################################################
  # PACKAGING & LINTERS
  #############################################################################


  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: WIPACrepo/wipac-dev-flake8-action@v1.0

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # NOTE: update, someday
      - uses: WIPACrepo/wipac-dev-mypy-action@v2.0
